# Generated by Django 5.2.10 on 2026-01-21 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.business')),
            ],
            options={
                'unique_together': {('business', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('BUSINESS', 'Business'), ('LEGAL', 'Legal')], default='BUSINESS', max_length=16)),
                ('locked', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.business')),
                ('business_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
        ),
    ]
