# Generated by Django 5.2.10 on 2026-01-21 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('SERVICE_STATION', 'Service Station'), ('IMPORT', 'Importing'), ('RETAIL', 'Retail')], default='RETAIL', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('ACCOUNTANT', 'Accountant'), ('LEGAL', 'Legal')], default='MANAGER', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'business')},
            },
        ),
    ]
